### ISSUE TITLE
"Could not find com.github.florent37:applicationprovider:1.0.0." error when build pipeline

### ISSUE THREAD

**Issue by gabrielle88** [kibotu/StreamingAndroidLogger#3]
I get this error when I try to build pipeline : `Could not find com.github.florent37:applicationprovider:1.0.0.
     Required by:
         project :app > com.github.kibotu:StreamingAndroidLogger:4.3.0`
Any idea about this? 
I know I use an older version of library but if I update it, all my logs are break. Any help how to get to the last version?

**Comment by kibotu** [comment]
hmm i didn't touch this in a hot minute, but i assume the dependency no longer resolves for some reason (probably so old due to jcenter shutdown)

**Comment by kibotu** [comment]
i've updated the dependencies and it should be working once again - cheers~
